The ``101-matrix_mul`` module
======================

Using ``matrix_mul``
-------------------

This is a doctest test file to test the matrix_mul function in
the module 100-matrix_mul.

	>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul
	>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]))
	[[ 7 10]
	 [15 22]]
	>>> print(lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]]))
	[[13 16]]
	>>> print(lazy_matrix_mul())
	[[1]]
	>>> print(lazy_matrix_mul([[1]]))
	[[1]]
	>>> try:
    	...	print(lazy_matrix_mul([[1, 2]], "Hello"))
	... except Exception as e:
	...	print(e)
	Scalar operands are not allowed, use '*' instead
	>>> try:
        ...     print(lazy_matrix_mul("Hello", [[1, 2]]))
        ... except Exception as e:
        ...     print(e)
        Scalar operands are not allowed, use '*' instead
	>>> try:
    	...	print(lazy_matrix_mul([], "Hello"))
	... except Exception as e:
	...	print(e)
	Scalar operands are not allowed, use '*' instead
	>>> try:
    	...	print(lazy_matrix_mul([[]], [[5, 6], [7, 8]]))
	... except Exception as e:
	...	print(e)
	shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)
	>>> try:
        ...     print(lazy_matrix_mul([[5, 6], [7, 8]], [[]]))
        ... except Exception as e:
        ...     print(e)
	shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)
	>>> try:
        ...     print(lazy_matrix_mul([[5, 6], [7, 8]], [[5, 6, 1], [7, 8]]))
        ... except Exception as e:
        ...     print(e)
	setting an array element with a sequence.
	>>> try:
        ...     print(lazy_matrix_mul([[5, 6, 1], [7, 8]]), [[5, 6], [7, 8]])
        ... except Exception as e:
        ...     print(e)
        setting an array element with a sequence.
	>>> try:
        ...     print(lazy_matrix_mul([[5, "6"], [7, 8]]), [[5, 6], [7, 8]])
        ... except Exception as e:
        ...     print(e)
	invalid data type for einsum
	>>> try:
        ...     print(lazy_matrix_mul([[5, 6], [7, 8]], [[5, "6"], [7, 8]]))
        ... except Exception as e:
        ...     print(e)
        invalid data type for einsum
	>>> try:
        ...     print(lazy_matrix_mul([[1, 2, 3], [3, 4, 5]], [[5, 6], [7, 8]]))
        ... except Exception as e:
        ...     print(e)
        shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)
